### ISSUE TITLE
Missing function arg

### ISSUE THREAD

**Issue by tildedennis** [SkyLined/cBugId#6]
Looks like one of the ftuLimitedAndAlignedMemoryDumpStartAddressAndSize calls in cBugReport_foAnalyzeException_STATUS_ACCESS_VIOLATION.py is missing a uPointerSize arg.

[cBugReport_foAnalyzeException_STATUS_ACCESS_VIOLATION.txt](https://github.com/SkyLined/cBugId/files/659634/cBugReport_foAnalyzeException_STATUS_ACCESS_VIOLATION.txt)

**Comment by SkyLined** [comment]
Thanks for the report and patch! This has been fixed:
https://github.com/SkyLined/cBugId/commit/12946c33c9e9c3c16f02ce0ae8912f5f96415885
